- name: Ensure system groups exists
  become: yes
  group: name={{service}} state=present

- name: Ensure system user exists
  become: yes
  user: name={{service}} group={{service}}

- name: Ensure .ssh dir exists
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  file: path=/home/{{service}}/.ssh state=directory owner={{service}} group={{service}} mode=0700

- name: Copy ssh deploy key
  become: yes
  copy: content="{{keys[service]}}" dest=/home/{{service}}/.ssh/id_rsa owner={{service}} group={{service}} mode=0400 force=yes

# ---- Deploy! ---- See: http://docs.ansible.com/ansible/deploy_helper_module.html
- name: Initialize the deploy root and gather facts
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  deploy_helper: path=/home/{{service}}

- name: Create the release dir
  become: yes
  file: path={{ deploy_helper.new_release_path }} state=directory owner={{service}} group={{service}} mode=0700

- name: Clone the project to the new release folder
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  git: dest={{ deploy_helper.new_release_path }}/src repo=ssh://git@github.com/{{repo}}.git version=HEAD depth=1 update=yes force=yes

- name: Add an unfinished file, to allow cleanup on successful finalize
  become: yes
  file: state=touch path={{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}

- name: Install our npm dependencies
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  shell: meteor npm install
  args:
    chdir: "{{ deploy_helper.new_release_path }}/src"
  notify:
    - Restart {{service}}

- name: Build bundle
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  command: meteor build .. --directory
  args:
    chdir: "{{ deploy_helper.new_release_path }}/src"
  notify:
    - Restart {{service}}

- name: Install meteor npm dependencies
  become: yes
  become_user: "{{service}}"
  vars:
    ansible_ssh_pipelining: true
  shell: meteor npm install
  args:
    chdir: "{{ deploy_helper.new_release_path }}/bundle/programs/server"
  notify:
    - Restart {{service}}

- name: Copy settings
  become: yes
  template: src=settings.json dest={{ deploy_helper.new_release_path }}/settings.json force=yes

- name: Finalize the deploy, removing the unfinished file and switching the symlink
  become: yes
  deploy_helper: path=/home/{{service}} release={{ deploy_helper.new_release }} state=finalize

# ---- END deploy_helper

- name: Copy Upstart config
  become: yes
  template: src=upstart/upstart.conf dest=/etc/init/{{service}}.conf mode=0644 force=yes

- name: Restart the app
  become: yes
  service: name={{service}} state=restarted enabled=yes

- name: Copy Nginx config
  become: yes
  template: src=nginx/nginx.conf dest=/etc/nginx/conf.d/{{service}}.conf mode=0644 force=yes
  notify:
    - Restart Nginx
