- name: Copy deploy keys
  sudo: yes
  copy: src=deploy-keys/ dest=/home/.ssh mode=0400 force=yes

- name: Remove Medialist clone
  sudo: yes
  command: rm -rf /home/app

- name: Remove Medialist build
  sudo: yes
  command: rm -rf /home/build

- name: Clone Medialist
  sudo: yes
  git: repo=git@github.com:Medialist/medialist-app.git dest=/home/app accept_hostkey=yes key_file=/home/.ssh/id_rsa

- name: Copy client settings over
  sudo: yes
  copy: src=client-settings.json dest=/home/app/client-settings.json force=yes

- name: Build Meteor bundle
  sudo: yes
  shell: meteor build /home/build --directory chdir=/home/app
  environment:
    METEOR_SETTINGS: meteor_settings

- name: Install Meteor NPM dependencies
  sudo: yes
  shell: npm install chdir=/home/build/bundle/programs/server

- name: Run Meteor app
  sudo: yes
  command: node main.js
  environment:
    ROOT_URL: http://localhost:3000
    MONGO_URL: mongodb://localhost:27017/medialist
  args:
    chdir: /home/build/bundle
