- name: Create Node distro directory
  sudo: yes
  file: path=/home/node state=directory

- name: Download Node distro
  sudo: yes
  get_url: url=http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz dest=/home/node/node.tar.gz

- name: Unarchive Node installer
  sudo: yes
  unarchive: src=/home/node/node.tar.gz dest=/home/node copy=no

- name: Install build dependencies
  sudo: yes
  apt: name=build-essential

- name: Configure Node installer
  sudo: yes
  command: ./configure
  args:
    chdir: /home/node/node-v0.10.36

- name: Make Node installer
  sudo: yes
  command: make
  args:
    chdir: /home/node/node-v0.10.36

- name: Install Node
  sudo: yes
  command: make install
  args:
    chdir: /home/node/node-v0.10.36
